### PR TITLE
Add UI component and filter to set visibility of multiple GPXObjects

### PR DESCRIPTION
**Pull request by nielstiben**
Before this feature, the only way to set the visibility of a GPXObject was by clicking on the tiny lamp icon on each GPXObject in the "Explorer" panel. With this new feature, it is possible to show or hide multiple GPXObject at once. By entering a keyword in the search bar, all entries which contain the search query will be hidden or shown.

___
**Example:**

Give an overview of all routes that _do not_ contain the word '`Var`'
example

### CODE REVIEW

**Comment by tboegi** [comment]
Thanks for the pull request
@rfuegen : Do you have any comments ?

**Comment by rfuegen** [comment]
@nielstiben thanks for your contribution! @tboegi no objections, please merge.

**Comment by tboegi** [comment]
Please give me some days to generate a new jar file

**Comment by tboegi** [comment]
@rfuegen @nielstiben (Or anybody else)

I made a "pre-release" here:
https://github.com/tboegi/GpsMaster/releases/tag/v0.63.36-rc0

If your time allows, please test the jar, so that we can make it official.

**Comment by nielstiben** [comment]
@tboegi Sorry for the late response.

I can verify that the jar works correctly on Ubuntu 18.04 LTS with OpenJDK 13.

**Pull request merged**
