### PR TITLE
Track filter panel improvement

### PR DESCRIPTION
**Pull request by nielstiben**
@rfuegen I implemented a dynamic track filter panel. It is visible when >=5 routes/tracks are loaded in the application and hidden when there are fewer than 5. The threshold can be set in the config, and the default is 5 for now.

In addition:
Fix NullPointerException for filtering tracks/route without a name.
Fix NullPointerException when no tracks/routes are loaded.
Fix bug where filter does not work when more than 1 GPX file is loaded.

### CODE REVIEW

**Comment by tboegi** [comment]
Thanks for the PR - I look into it as soon as possible.

**Comment by tboegi** [comment]
@rfuegen :  The PR merges cleanly - no objections from my side.
Do you have any objections ?

**Comment by rfuegen** [comment]
hi niels, if I'm not mistaken, updateTrackFilterPanelVisibility() should also be called when handling the PCE_NEWGPX event. otherwise, no objections. thanks.

**Comment by rfuegen** [comment]
one more: please set default config value to 10.

**Comment by tboegi** [comment]
I merged it manually and pushed the result to the dev branch
- please check @rfuegen and @nielstiben if the config is as it should be. Thanks

**Pull request merged**
